FROM node:22-alpine

WORKDIR /app

RUN npm install -g kysely@latest pg tsx

COPY ./migrations ./migrations
COPY ./.config/kysely.config.ts ./.config/

ENTRYPOINT ["tsx", "kysely", "migrate", "latest"]
