name: Deploy to Stage

on:
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy to Stage
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v3

      - name: 🚀 Deploy to Stage via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.STAGE_IP }}
          username: ${{ secrets.STAGE_USER }}
          key: ${{ secrets.STAGE_PRIVATE_KEY }}
          script: |
            cd ${{ secrets.PROJECT_DIRECTORY }} 
            git pull origin main
            docker compose -f stage.docker-compose.yml up -d --build
